import type { OptionCatalogEntry } from "./types.js";

export const OPTION_CATALOG: OptionCatalogEntry[] = [
  {
    key: "model",
    envVar: "CLAUDE_MODEL",
    label: "Model",
    hint: "Which Claude model to use",
    example: '"sonnet", "opus", "haiku", or full ID',
  },
  {
    key: "appendPrompt",
    envVar: "CLAUDE_APPEND_PROMPT",
    label: "Behavior prompt",
    hint: "Instructions appended to the default Claude Code system prompt",
    example: '"Always explain your reasoning step by step."',
  },
  {
    key: "systemPrompt",
    envVar: "CLAUDE_SYSTEM_PROMPT",
    label: "Full system prompt",
    hint: "Completely replaces the default system prompt (use appendPrompt instead to keep defaults)",
    example: '"You are a security auditor..."',
  },
  {
    key: "allowedTools",
    envVar: "CLAUDE_ALLOWED_TOOLS",
    label: "Available tools",
    hint: "Restrict agent to only these tools (comma-separated)",
    example: '"Read,Grep,Glob" for read-only; "Bash,Read,Write,Edit,Grep,Glob" for full access',
  },
  {
    key: "disallowedTools",
    envVar: "CLAUDE_DISALLOWED_TOOLS",
    label: "Blocked tools",
    hint: "These tools are removed (comma-separated)",
    example: '"WebFetch,WebSearch" to block network access',
  },
  {
    key: "cwd",
    envVar: "CLAUDE_CWD",
    label: "Working directory",
    hint: "Default directory the agent operates in",
    example: '"/home/user/project"',
  },
  {
    key: "additionalDirs",
    envVar: "CLAUDE_ADDITIONAL_DIRS",
    label: "Additional directories",
    hint: "Extra directories the agent can access (comma-separated)",
    example: '"/shared/libs,/data"',
  },
  {
    key: "maxTurns",
    envVar: "CLAUDE_MAX_TURNS",
    label: "Max turns",
    hint: "Maximum conversation turns per invocation",
    example: '"10" for quick tasks, "50" for complex ones',
  },
  {
    key: "maxBudgetUsd",
    envVar: "CLAUDE_MAX_BUDGET_USD",
    label: "Budget cap (USD)",
    hint: "Maximum spend per invocation",
    example: '"0.05" for cheap, "2.0" for complex tasks',
  },
  {
    key: "effort",
    envVar: "CLAUDE_EFFORT",
    label: "Reasoning effort",
    hint: "How hard the agent thinks",
    example: '"low" (fast), "medium", "high" (thorough), "max" (deepest)',
  },
  {
    key: "plugins",
    envVar: "CLAUDE_PLUGINS",
    label: "Plugins",
    hint: "Local plugin paths (comma-separated)",
    example: '"/path/to/my-plugin"',
  },
  {
    key: "permissionMode",
    envVar: "CLAUDE_PERMISSION_MODE",
    label: "Permission mode",
    hint: "How tool executions are authorized",
    example: '"bypassPermissions" (auto-approve), "acceptEdits" (auto-approve edits only), "plan" (no execution)',
  },
  {
    key: "persistSession",
    envVar: "CLAUDE_PERSIST_SESSION",
    label: "Persist sessions",
    hint: "Save sessions for later resume via _reply tool",
    example: '"true" (default) or "false"',
  },
  {
    key: "settingSources",
    envVar: "CLAUDE_SETTING_SOURCES",
    label: "Setting sources",
    hint: "Which settings files to load (comma-separated)",
    example: '"user,project" to load CLAUDE.md and user settings',
  },
  {
    key: "mcpServers",
    envVar: "CLAUDE_MCP_SERVERS",
    label: "Inner MCP servers",
    hint: "MCP servers available to the inner agent (JSON)",
    example: '\'{"db":{"command":"node","args":["db-server.js"]}}\'',
  },
  {
    key: "betas",
    envVar: "CLAUDE_BETAS",
    label: "Beta features",
    hint: "Enable beta capabilities (comma-separated)",
    example: '"context-1m-2025-08-07" for 1M context window',
  },
  {
    key: "apiKey",
    envVar: "ANTHROPIC_API_KEY",
    label: "API key",
    hint: "Anthropic API key for this agent (overrides inherited auth)",
    example: '"sk-ant-api03-..." — leave unset to inherit from parent',
  },
  {
    key: "oauthToken",
    envVar: "CLAUDE_CODE_OAUTH_TOKEN",
    label: "OAuth token",
    hint: "Claude Code OAuth token for this agent (overrides inherited auth)",
    example: '"sk-ant-oat01-..." — leave unset to inherit from parent',
  },
  {
    key: "timelineDir",
    envVar: "CLAUDE_TIMELINE_DIR",
    label: "Timeline directory",
    hint: "Where to store the cross-agent timeline index (shared by all agents in a workflow)",
    example: '"~/.claude-octopus/timelines" (default)',
  },
];
